# Generated by Django 5.1.1 on 2024-09-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Наименование')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, verbose_name='Широта')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['longitude', 'latitude'],
                'indexes': [models.Index(fields=['name'], name='cities_city_name_a4d1d7_idx')],
            },
        ),
    ]
